### ISSUE TITLE
Zenzo MasterNode Guide targets an unreachable fork link

### ISSUE THREAD

**Issue by cguillemette** [Zenzo-Ecosystem/Guides#5]
On this page https://github.com/Zenzo-Ecosystem/Guides/blob/master/Zenzo_Masternode_Guide.md,
right under the section "Enter this command to copy the Masternode installation script and install a single ZENZO (ZNZ) Masternode:", the link https://github.com/Zenzo-Ecosystem/vps.git is not reachable. As if the fork was deleted.

**Comment by YuurinBee** [comment]
Thank you for sharing @cguillemette, @liray-unendlich can you check and update this please?
